#!/usr/bin/env node

"use strict";

var path      = require("path"),
    fs        = require("fs"),
    Commander = require("commander"),

    Package   = require("./package.json"),
    rlode     = require(path.join( path.dirname( fs.realpathSync(__filename) ), "rlode.js" )),

    Result;





Commander
   .version(Package.version)
   .option("-g, --glob [glob string]", "Glob string for file list matching")
   .parse(process.argv);



Result = rlode.scan_glob(Commander.glob, "options bar");

// console.log('Matches:' + JSON.stringify(Result, undefined, 2));
rlode.nice_print(Result);
