
// http://compass-style.org/index/functions/
// "sass functions"

// these are not normally checked for by this tool, whose purpose is to root out compass, not sass (mostly
// to support people trying to move to libsass/node_sass/etc;) however, as long as the tool is there . . .

module.exports = [
  "abs(",
  "adjust-color(",
  "adjust-hue(",
  "alpha(",
  "append(",
  "blue(",
  "ceil(",
  "change-color(",
  "comparable(",
  "complement(",
  "darken(",
  "desaturate(",
  "fade-in(",
  "fade-out(",
  "floor(",
  "grayscale(",
  "green(",
  "hsl(",
  "hsla(",
  "hue(",
  "if(",
  "index(",
  "invert(",
  "join(",
  "length(",
  "lighten(",
  "lightness(",
  "mix(",
  "nth(",
  "opacify(",
  "opacity(",
  "percentage(",
  "quote(",
  "red(",
  "rgb(",
  "rgba(",
  "round(",
  "saturate(",
  "saturation(",
  "scale-color(",
  "transparentize(",
  "type-of(",
  "unit(",
  "unitless(",
  "unquote(",
  "zip"
];
